package io.greencap.k8s.domain.user;

import java.util.Set;

public enum Permission {

    // Project — Topology
    TOPOLOGY_VIEW,

    // Project — Manifest
    MANIFEST_EDIT,

    // Project — Workloads
    WORKLOADS_DEPLOYMENTS_VIEW,
    WORKLOADS_DEPLOYMENTS_SCALE,
    WORKLOADS_DEPLOYMENTS_RESTART,
    WORKLOADS_DEPLOYMENTS_ROLLBACK,
    WORKLOADS_DEPLOYMENTS_DELETE,
    WORKLOADS_STATEFULSETS_VIEW,
    WORKLOADS_STATEFULSETS_SCALE,
    WORKLOADS_STATEFULSETS_RESTART,
    WORKLOADS_STATEFULSETS_ROLLBACK,
    WORKLOADS_STATEFULSETS_DELETE,
    WORKLOADS_REPLICASETS_VIEW,
    WORKLOADS_REPLICASETS_DELETE,
    WORKLOADS_PODS_VIEW,
    WORKLOADS_PODS_DELETE,
    WORKLOADS_JOBS_VIEW,
    WORKLOADS_JOBS_DELETE,
    WORKLOADS_CRONJOBS_VIEW,
    WORKLOADS_CRONJOBS_RUN_NOW,
    WORKLOADS_CRONJOBS_SUSPEND,
    WORKLOADS_CRONJOBS_DELETE,

    // Project — Networking
    NETWORKING_SERVICES_VIEW,
    NETWORKING_SERVICES_DELETE,
    NETWORKING_INGRESS_VIEW,
    NETWORKING_INGRESS_DELETE,

    // Project — Parameters
    PARAMETERS_CONFIGMAPS_VIEW,
    PARAMETERS_CONFIGMAPS_DELETE,
    PARAMETERS_SECRETS_VIEW,
    PARAMETERS_SECRETS_DELETE,

    // Project — Auto Scaling
    AUTOSCALING_HORIZONTALSCALER_VIEW,
    AUTOSCALING_HORIZONTALSCALER_WRITE,
    AUTOSCALING_HORIZONTALSCALER_DELETE,

    // Project — Storage
    STORAGE_PVC_VIEW,
    STORAGE_PVC_DELETE,

    // Observability
    OBSERVABILITY_DASHBOARD_VIEW,
    OBSERVABILITY_EVENTS_VIEW,
    OBSERVABILITY_METRICS_VIEW,

    // Global
    GLOBAL_CLUSTERS_VIEW,
    GLOBAL_CLUSTERS_WRITE,
    GLOBAL_INFRASTRUCTURE_VIEW,
    GLOBAL_INFRASTRUCTURE_CORDON,

    // Settings
    SETTINGS_USERS_VIEW,
    SETTINGS_USERS_WRITE,
    SETTINGS_PLATFORM_VIEW;

    public static Set<Permission> allPermissions() {
        return Set.of(values());
    }

    public static Set<Permission> operatorPermissions() {
        return Set.of(
                TOPOLOGY_VIEW,
                MANIFEST_EDIT,
                WORKLOADS_DEPLOYMENTS_VIEW, WORKLOADS_DEPLOYMENTS_SCALE, WORKLOADS_DEPLOYMENTS_RESTART,
                WORKLOADS_DEPLOYMENTS_ROLLBACK, WORKLOADS_DEPLOYMENTS_DELETE,
                WORKLOADS_STATEFULSETS_VIEW, WORKLOADS_STATEFULSETS_SCALE, WORKLOADS_STATEFULSETS_RESTART,
                WORKLOADS_STATEFULSETS_ROLLBACK, WORKLOADS_STATEFULSETS_DELETE,
                WORKLOADS_REPLICASETS_VIEW, WORKLOADS_REPLICASETS_DELETE,
                WORKLOADS_PODS_VIEW, WORKLOADS_PODS_DELETE,
                WORKLOADS_JOBS_VIEW, WORKLOADS_JOBS_DELETE,
                WORKLOADS_CRONJOBS_VIEW, WORKLOADS_CRONJOBS_RUN_NOW, WORKLOADS_CRONJOBS_SUSPEND, WORKLOADS_CRONJOBS_DELETE,
                NETWORKING_SERVICES_VIEW, NETWORKING_SERVICES_DELETE,
                NETWORKING_INGRESS_VIEW, NETWORKING_INGRESS_DELETE,
                PARAMETERS_CONFIGMAPS_VIEW, PARAMETERS_CONFIGMAPS_DELETE,
                PARAMETERS_SECRETS_VIEW, PARAMETERS_SECRETS_DELETE,
                AUTOSCALING_HORIZONTALSCALER_VIEW, AUTOSCALING_HORIZONTALSCALER_WRITE, AUTOSCALING_HORIZONTALSCALER_DELETE,
                STORAGE_PVC_VIEW, STORAGE_PVC_DELETE,
                OBSERVABILITY_DASHBOARD_VIEW, OBSERVABILITY_EVENTS_VIEW, OBSERVABILITY_METRICS_VIEW,
                GLOBAL_CLUSTERS_VIEW, GLOBAL_CLUSTERS_WRITE,
                GLOBAL_INFRASTRUCTURE_VIEW, GLOBAL_INFRASTRUCTURE_CORDON,
                SETTINGS_PLATFORM_VIEW
        );
    }

    public static Set<Permission> viewerPermissions() {
        return Set.of(
                TOPOLOGY_VIEW,
                WORKLOADS_DEPLOYMENTS_VIEW,
                WORKLOADS_STATEFULSETS_VIEW,
                WORKLOADS_REPLICASETS_VIEW, WORKLOADS_PODS_VIEW,
                WORKLOADS_JOBS_VIEW, WORKLOADS_CRONJOBS_VIEW,
                NETWORKING_SERVICES_VIEW, NETWORKING_INGRESS_VIEW,
                PARAMETERS_CONFIGMAPS_VIEW, PARAMETERS_SECRETS_VIEW,
                AUTOSCALING_HORIZONTALSCALER_VIEW,
                STORAGE_PVC_VIEW,
                OBSERVABILITY_DASHBOARD_VIEW, OBSERVABILITY_EVENTS_VIEW, OBSERVABILITY_METRICS_VIEW,
                GLOBAL_CLUSTERS_VIEW,
                GLOBAL_INFRASTRUCTURE_VIEW,
                SETTINGS_PLATFORM_VIEW
        );
    }
}
