apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: greencap-platform
  labels:
    app.kubernetes.io/part-of: greencap-platform
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
