apiVersion: v1
kind: Service
metadata:
  name: greencap-db
  namespace: greencap-platform
  labels:
    app.kubernetes.io/part-of: greencap-platform
    app.kubernetes.io/component: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
