apiVersion: batch/v1
kind: Job
metadata:
  name: create-db-job
  namespace: postgresql
spec:
  template:
    spec:
      containers:
      - name: psql-client
        image: postgres:17.6
        command: ["/bin/bash", "-c"]
        args:
        - |
          sleep 5;
          psql "postgresql://postgres@postgres-17" \
            -c "CREATE DATABASE ecom_python;"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-17 
              key: POSTGRES_PASSWORD 
      restartPolicy: OnFailure