-- Granular permission model: replaces the single role column with a set of named permissions per user.
-- Existing users are seeded based on their current role before the column is dropped.

CREATE TABLE user_permissions (
    user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    permissions VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id, permissions)
);

-- ADMIN → all permissions
INSERT INTO user_permissions (user_id, permissions)
SELECT u.id, p.permission
FROM users u
CROSS JOIN (VALUES
    ('TOPOLOGY_VIEW'),
    ('WORKLOADS_DEPLOYMENTS_VIEW'), ('WORKLOADS_DEPLOYMENTS_SCALE'), ('WORKLOADS_DEPLOYMENTS_RESTART'),
    ('WORKLOADS_REPLICASETS_VIEW'), ('WORKLOADS_PODS_VIEW'),
    ('NETWORKING_SERVICES_VIEW'),
    ('PARAMETERS_CONFIGMAPS_VIEW'), ('PARAMETERS_SECRETS_VIEW'),
    ('AUTOSCALING_HORIZONTALSCALER_VIEW'), ('AUTOSCALING_HORIZONTALSCALER_WRITE'),
    ('STORAGE_PVC_VIEW'),
    ('OBSERVABILITY_DASHBOARD_VIEW'), ('OBSERVABILITY_EVENTS_VIEW'), ('OBSERVABILITY_METRICS_VIEW'),
    ('SETTINGS_CLUSTERS_VIEW'), ('SETTINGS_CLUSTERS_WRITE'),
    ('SETTINGS_INFRASTRUCTURE_VIEW'),
    ('SETTINGS_USERS_VIEW'), ('SETTINGS_USERS_WRITE'),
    ('SETTINGS_PLATFORM_VIEW')
) AS p(permission)
WHERE u.role = 'ADMIN';

-- OPERATOR → all except user management
INSERT INTO user_permissions (user_id, permissions)
SELECT u.id, p.permission
FROM users u
CROSS JOIN (VALUES
    ('TOPOLOGY_VIEW'),
    ('WORKLOADS_DEPLOYMENTS_VIEW'), ('WORKLOADS_DEPLOYMENTS_SCALE'), ('WORKLOADS_DEPLOYMENTS_RESTART'),
    ('WORKLOADS_REPLICASETS_VIEW'), ('WORKLOADS_PODS_VIEW'),
    ('NETWORKING_SERVICES_VIEW'),
    ('PARAMETERS_CONFIGMAPS_VIEW'), ('PARAMETERS_SECRETS_VIEW'),
    ('AUTOSCALING_HORIZONTALSCALER_VIEW'), ('AUTOSCALING_HORIZONTALSCALER_WRITE'),
    ('STORAGE_PVC_VIEW'),
    ('OBSERVABILITY_DASHBOARD_VIEW'), ('OBSERVABILITY_EVENTS_VIEW'), ('OBSERVABILITY_METRICS_VIEW'),
    ('SETTINGS_CLUSTERS_VIEW'), ('SETTINGS_CLUSTERS_WRITE'),
    ('SETTINGS_INFRASTRUCTURE_VIEW'),
    ('SETTINGS_PLATFORM_VIEW')
) AS p(permission)
WHERE u.role = 'OPERATOR';

-- VIEWER → view-only permissions
INSERT INTO user_permissions (user_id, permissions)
SELECT u.id, p.permission
FROM users u
CROSS JOIN (VALUES
    ('TOPOLOGY_VIEW'),
    ('WORKLOADS_DEPLOYMENTS_VIEW'),
    ('WORKLOADS_REPLICASETS_VIEW'), ('WORKLOADS_PODS_VIEW'),
    ('NETWORKING_SERVICES_VIEW'),
    ('PARAMETERS_CONFIGMAPS_VIEW'), ('PARAMETERS_SECRETS_VIEW'),
    ('AUTOSCALING_HORIZONTALSCALER_VIEW'),
    ('STORAGE_PVC_VIEW'),
    ('OBSERVABILITY_DASHBOARD_VIEW'), ('OBSERVABILITY_EVENTS_VIEW'), ('OBSERVABILITY_METRICS_VIEW'),
    ('SETTINGS_CLUSTERS_VIEW'),
    ('SETTINGS_INFRASTRUCTURE_VIEW'),
    ('SETTINGS_PLATFORM_VIEW')
) AS p(permission)
WHERE u.role = 'VIEWER';

ALTER TABLE users DROP COLUMN role;
