-- Grants GLOBAL_INFRASTRUCTURE_PV_DELETE to users with GLOBAL_INFRASTRUCTURE_CORDON (ADMIN, OPERATOR).
INSERT INTO user_permissions (user_id, permissions)
SELECT user_id, 'GLOBAL_INFRASTRUCTURE_PV_DELETE'
FROM user_permissions
WHERE permissions = 'GLOBAL_INFRASTRUCTURE_CORDON'
ON CONFLICT DO NOTHING;
