apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greencap-demo
  namespace: greencap-demo
  labels:
    app.kubernetes.io/name: greencap-demo
    app.kubernetes.io/part-of: greencap-demo
    app.kubernetes.io/managed-by: greencap
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: greencap-demo.local
    http:
      paths:
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend
            port:
              number: 80
