apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greencap-demo
  namespace: greencap-demo
  labels:
    app.kubernetes.io/name: greencap-demo
    app.kubernetes.io/managed-by: greencap
spec:
  ingressClassName: nginx
  rules:
  - host: greencap-demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 80
