Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "greencap-test"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "greencap-test"
    vb.memory = 4096
    vb.cpus   = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -q
    apt-get upgrade -y -q
    apt-get autoremove -y -q
  SHELL
end
